In [1]:
import numpy as np
import pandas as pd

In [8]:
x=[10,20,30,40]
y= pd.Series(x)
y

0    10
1    20
2    30
3    40
dtype: int64

In [9]:
type(y)

pandas.core.series.Series

In [10]:
data = [
    {'Name': 'John', 'Age': 28, 'City': 'New York', 'Salary': 65000 },
    {'Name': 'Anna', 'Age': 34, 'City': 'Paris', 'Salary': 70000  },
    {'Name': 'Peter', 'Age': 29, 'City': 'Berlin', 'Salary': 62000 },
]
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df['Name']

0     John
1     Anna
2    Peter
Name: Name, dtype: object

In [13]:
type(df['Name'])

pandas.core.series.Series

In [14]:
df.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [15]:
type(df.loc[0])

pandas.core.series.Series

In [17]:
df['Name']= ['Ram', 'Shyam', 'Hari']

In [18]:
df

    Name  Age      City  Salary
0    Ram   28  New York   65000
1  Shyam   34     Paris   70000
2   Hari   29    Berlin   62000

In [19]:
type(df['Name'])

pandas.core.series.Series